apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: secret-job
  namespace: web
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: job
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-status: "update"
            vault.hashicorp.com/role: 'internal-app'
            vault.hashicorp.com/agent-inject-secret-database-config.sh: 'internal/data/database/config'
            # Environment variable export template
            vault.hashicorp.com/agent-inject-template-database-config.sh: |
              {{ with secret "internal/data/database/config" -}}
                export username="{{ .Data.data.username }}"
                export password="{{ .Data.data.password }}"
              {{- end }}
        spec:
          serviceAccountName: internal-app
          containers:
          - name: job
            image: alpine:latest
            args:
              ['sh', '-c', 'source /vault/secrets/database-config.sh ; echo "username=$username password=$password" ; sleep 3600']
          restartPolicy: OnFailure